using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Tilemaps;

/// <summary>
/// Class containing the methods responsible for applying the assets to the map.
/// </summary>
public class TileMapVisualizer : MonoBehaviour
{
    /// <summary>
    /// Variable that stores the tile-map that defines the floor.
    /// </summary>
    [SerializeField]
    private Tilemap floorTilemap;
    /// <summary>
    /// Variable that stores the asset used for the floor
    /// </summary>
    [SerializeField]
    private TileBase floorTile;

    /// <summary>
    /// Method responsible for adding the corresponding asset to the tilemap using the path information generated by the RandomWalk algorithm.
    /// </summary>
    /// <param name="floorPositions">The location information for the current cell/tile.</param>
    public void PaintFloorTiles(IEnumerable<Vector2> floorPositions)
    {
        PaintTiles(floorPositions, floorTilemap, floorTile);
    }

    /// <summary>
    /// Method responsible to painting a the assets onto each tile of the map.
    /// </summary>
    /// <param name="positions">List of positions/locations where an asset must be applied.</param>
    /// <param name="tilemap">Tile-map that the asset will be applied to.</param>
    /// <param name="tile">The asset that will be used.</param>
    private void PaintTiles(IEnumerable<Vector2> positions, Tilemap tilemap, TileBase tile)
    {
        foreach (var position in positions)
        {
            PaintSingleTile(tilemap, tile, position);
        }
    }

    /// <summary>
    /// Method that localizes the absolute location of a tile to a cell, then applies the asset to a single cell on the tilemap.
    /// </summary>
    /// <param name="tilemap">The tile-map that the asset will be applied to.</param>
    /// <param name="tile">The corresponding asset that will be applied.</param>
    /// <param name="position">The location of the cell.</param>
    private void PaintSingleTile(Tilemap tilemap, TileBase tile, Vector2 position)
    {
        var tilePosition = tilemap.WorldToCell((Vector3)position);
        // Log the localized cell position and the absolute position.
        Debug.Log(tilePosition + " | " + position);
        tilemap.SetTile(tilePosition, tile);
    }

    /// <summary>
    /// Method used to clear the entire tile-map of assets.
    /// </summary>
    public void Clear()
    {
        floorTilemap.ClearAllTiles();
    }
}
